In [59]:
import pandas as pd #pd refers to pandas

In [60]:
df = pd.read_csv("pokemon_data.csv") #df = dataframe. delimiter = "\t"

In [61]:
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

## Reading Data Frames

In [62]:
df.columns #Reading Headers

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [63]:
#print(df[['Name', 'Type 1', 'Type 2']]) #Reading each column

In [64]:
#Read each row
df.loc[df['Type 1'] == "Fire"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

## Describing data

In [65]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [66]:
df.sort_values('Type 1')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
600,540,Sewaddle,Bug,Grass,45,53,70,40,60,42,5,False
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False
457,412,Burmy,Bug,NaN,40,29,45,29,45,36,4,False
132,123,Scyther,Bug,Flying,70,110,80,55,80,105,1,False
656,595,Joltik,Bug,Electric,50,47,50,57,50,65,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
172,158,Totodile,Water,NaN,50,65,64,44,48,43,2,False
610,550,Basculin,Water,NaN,70,92,65,80,55,98,5,False
145,134,Vaporeon,Water,NaN,130,65,60,110,95,65,1,False
574,515,Panpour,Water,NaN,50,53,48,53,48,64,5,False
184,170,Chinchou,Water,Electric,75,38,38,56,56,67,2,False

## Making changes to the data

In [58]:
#df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df ['Sp. Atk'] + df['Sp. Def'] + df['Speed']
#print(df['Total'])

In [71]:
df['Total'] = df.iloc[:,4:10].sum(axis = 1)

In [72]:
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  Total
0         65       65     45           1      False    318
1         80       80     60           1      False    405
2        100      100     80           1      False    525
3        122      120     80           1      False    625
4         60       50     65           1      False    309
..       ...      ...    ...         ...        ...    ...
795      100      150     50           6       True    600
796      160      110    110           6       True    700
797      150      130     70           6       True    600
798      170      130     80           6       True    680
799      130       90     70           6       True    600

[800 rows x 13 columns]